[project]
name = "projek-pemodelan-wisnu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "simpy>=4.1.1",
    "statistics>=1.0.3.5",
    "streamlit>=1.52.2",
]
