[project]
name = "projek-pemodelan-wisnu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "simpy>=4.1.1",
    "statistics>=1.0.3.5",
]
